### ISSUE TITLE
Selenium Java RESTfull Service Integration with AngularJS

### ISSUE THREAD

**Issue by ekiziltas** [elma-org/elma#1]
Using JAVA RestFull API, it is foreseen that there would be a interface that permits AngularJS queries with job task JSON data, then popuplates them into relevant fields and returns back as a response JSON data with the full of data including manually changed items (not only gap but whole data).

Best Regards,

Eray

**Comment by ozgen** [comment]
WebService is ready but it is not tested with angular js.

**Comment by ekiziltas** [comment]
Test successfull
